site_name: CorkScrew Docs
theme: readthedocs
pages:
  - Home: index.md
  - Cmdlets:
    - Get-CsConfiguration: cmdlets/Get-CsConfiguration.md
    - Get-GithubRepo: cmdlets/Get-GithubRepo.md
    - Get-Ninite: cmdlets/Get-Ninite.md
    - Get-OsVersion: cmdlets/Get-OsVersion.md
    - Invoke-ElevatedProcess: cmdlets/Invoke-ElevatedProcess.md
    - Invoke-FuriousIp: cmdlets/Invoke-FuriousIp.md
    - Invoke-NotepadPlusPlus: cmdlets/Invoke-NotepadPlusPlus.md
    - New-CsConfiguration: cmdlets/New-CsConfiguration.md
    - New-EncryptedString: cmdlets/New-EncryptedString.md
    - New-EncryptionKey: cmdlets/New-EncryptionKey.md
    - New-PsModule: cmdlets/New-PsModule.md
    - Test-UserElevation: cmdlets/Test-UserElevation.md
    - Write-CustomLog: cmdlets/Write-CustomLog.md

